# Store URLs, API endpoints, and file names# config.yaml
project_name: "osteosarcoma_proteomics_ml"

# Directory Structure (Python will use this to ensure folders exist)
directories:
  raw_data: "data/01_raw"
  mapped_data: "data/02_mapped"
  processed_data: "data/03_processed"
  logs: "logs"

# Primary Data Sources
datasets:
  MassIVE:
    # SENT AN EMAIL REQUESTING PUBLIC RELEASE TO MASSIVE(UCSD)
    source: "https://www.mdpi.com/2073-4409/12/17/2179"
    project_accession: "MSV000091434"
    api_endpoint: "https://massive.ucsd.edu/ProteoSAFe/static/massive.jsp?redirect=auth"
    target_extensions: [".txt", ".tsv", ".mzTab"] 
    
  zhang_chemoresponse:
  # Ready
    source: "https://www.frontiersin.org/journals/oncology/articles/10.3389/fonc.2025.1597750/full"
    doi: "10.3389/fonc.2025.1597750"
    supplementary_url: "https://public-pages-files-2025.frontiersin.org/articles/1597750/file/Table_1.xlsx/1597750_table_1/1"
    
  lee_phospho_drug:
  # Ready
    source: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10883282/#Sec2"
    doi: "10.1038/s44320-023-00004-7"
    files:
      # Drug response metrics(EV3). Total protein abundance(EV4). Phosphorylation state(EV5).
      local_path: "data/raw/"
      local_path: "data/raw/"
      baseline_phospho_ev5: "https://pmc.ncbi.nlm.nih.gov/articles/instance/10883282/bin/44320_2023_4_MOESM6_ESM.xlsx"

  depmap_broad:
    source: "https://depmap.org/portal/data_page/?tab=allData"
    local_path: "data/raw/GDSC2AUCMatrix.csv"